# Generated by Django 2.1.5 on 2019-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIPSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_authentication_token', models.CharField(help_text='Use the OAuth Access Token found in the Slack integration.', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'WIP settings',
            },
        ),
    ]
