# Generated by Django 2.2.1 on 2019-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wipsettings',
            name='timesheet_check_range',
            field=models.PositiveIntegerField(default=7, help_text='Specifies the number of days to check for missing past timesheet entries.'),
        ),
    ]
