# Generated by Django 2.1.2 on 2018-10-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180927_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moneyworks_cost_centre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
