# Generated by Django 2.2 on 2019-05-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_moneyworks_cost_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_timesheet_reminders',
            field=models.BooleanField(default=False, help_text='Designates whether this user requires a nudge to remind them fill in their timesheet. ', verbose_name='Timesheet reminders'),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
