# Generated by Django 2.1.1 on 2018-09-18 11:51

import authentication.middleware.current_user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0002_jobnote_tasknote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'job statuses'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['order'], 'verbose_name_plural': 'task statuses'},
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='user',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasknote',
            name='user',
            field=models.ForeignKey(default=authentication.middleware.current_user.get_current_user, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
