# Generated by Django 2.1.1 on 2018-09-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0003_auto_20180925_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrelationship',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='taskassignee',
            options={'ordering': ['user']},
        ),
    ]
