# Generated by Django 2.1.1 on 2018-09-27 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0006_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9 ]+$')]),
        ),
    ]
