# Generated by Django 2.1.1 on 2018-09-20 13:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0007_auto_20180920_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='allocated_hours',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
