# Generated by Django 2.1.1 on 2018-09-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0008_auto_20180920_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignees',
        ),
        migrations.AlterField(
            model_name='jobrelationship',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='wip.Job'),
        ),
        migrations.AlterField(
            model_name='taskassignee',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='wip.Task'),
        ),
    ]
