# Generated by Django 2.1.1 on 2018-10-02 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0008_auto_20181001_1059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timedailysignoff',
            unique_together={('date', 'user')},
        ),
    ]
