# Generated by Django 2.1.1 on 2018-09-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0009_auto_20180920_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wip.Job'),
        ),
    ]
