# Generated by Django 2.1.1 on 2018-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0009_auto_20181002_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='allow_new_clock_entries',
            field=models.BooleanField(default=True),
        ),
    ]
