# Generated by Django 2.1.1 on 2018-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0010_auto_20180921_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='not_chargeable',
            field=models.BooleanField(default=False),
        ),
    ]
