# Generated by Django 2.1.1 on 2018-09-24 15:37

from django.db import migrations
import wip.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0011_task_not_chargeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='colour',
            field=wip.fields.ColorField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
