# Generated by Django 2.1.1 on 2018-09-24 15:45

from django.db import migrations
import wip.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0012_client_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='colour',
            field=wip.fields.ColorField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
