# Generated by Django 2.1.2 on 2018-10-10 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0012_auto_20181005_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='taskassignee',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='taskassignee',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskassignee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
