# Generated by Django 2.1.2 on 2018-10-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0013_auto_20181010_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobnote',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='tasknote',
            options={'ordering': ['-updated_at']},
        ),
    ]
