# Generated by Django 2.1.2 on 2018-10-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0014_auto_20181012_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
