# Generated by Django 2.1.2 on 2018-10-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0015_jobstatus_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskassignee',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='taskassignee',
            name='order',
        ),
    ]
