# Generated by Django 2.1.3 on 2018-11-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0020_auto_20181108_1258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timedailysignoff',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timedailysignoff',
            name='user',
        ),
        migrations.DeleteModel(
            name='TimeDailySignoff',
        ),
    ]
