# Generated by Django 2.1.3 on 2018-11-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0023_auto_20181122_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
    ]
