# Generated by Django 2.1.3 on 2018-11-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0024_auto_20181123_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hours', models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=10, null=True)),
                ('time_spent_hours', models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=10, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='wip.Job')),
            ],
        ),
    ]
