# Generated by Django 2.1.3 on 2018-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0025_jobtiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.FloatField(default=16384),
        ),
    ]
