# Generated by Django 2.1.4 on 2018-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0026_auto_20181129_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='notify_job_relationships',
            field=models.BooleanField(default=False, help_text='Send an email to all job relationships when a task changes to this status'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='notify_task_assignees',
            field=models.BooleanField(default=False, help_text='Send an email to all task assignees when a task changes to this status'),
        ),
    ]
