# Generated by Django 2.1.5 on 2019-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0027_auto_20181213_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
