# Generated by Django 2.1.5 on 2019-03-22 16:59

from django.db import migrations, models
import wip.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0029_taskstatus_show_on_job_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='colour',
            field=wip.fields.ColorField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='icon',
            field=models.CharField(blank=True, help_text='An icon representing this status', max_length=255, null=True),
        ),
    ]
