# Generated by Django 2.1.5 on 2019-03-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from reversion.models import Version


def set_default_created_by(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    Task = apps.get_model('wip', 'Task')

    for task in Task.objects.all():
        initial_revision = Version.objects.get_for_object(task).first()

        if initial_revision and initial_revision.revision and initial_revision.revision.user:
            user = User.objects.get(pk=initial_revision.revision.user.pk)
            task.created_by = user
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wip', '0030_auto_20190322_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_created_by)
    ]
