# Generated by Django 2.1.5 on 2019-03-28 16:37

from django.db import migrations


def set_default_created_by(apps, schema_editor):
    Revision = apps.get_model('reversion', 'Revision')
    Task = apps.get_model('wip', 'Task')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    db_alias = schema_editor.connection.alias

    for task in Task.objects.using(db_alias).all():
        content_type = ContentType.objects.get_for_model(task)
        initial_revision = (
            Revision.objects.using(db_alias)
            .filter(version__object_id=task.pk, version__content_type_id=content_type.pk)
            .order_by('date_created').first()
        )

        if initial_revision and initial_revision.user:
            task.created_by = initial_revision.user
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wip', '0031_task_created_by'),
    ]

    operations = [
        migrations.RunPython(set_default_created_by)
    ]
